#include "general.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

/* ── I2C handles (generated by CubeMX) ─────────────────────────
   hi2c1 : PB6/PB7  → MPU6500 + HMC5883L
   hi2c2 : PB10/PB11 → SSD1306 OLED                             */
extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c2;

/* ── Global map (declared here, extern'd in general.h) ─────────*/
Map g_map;

/* ── Module-private state ───────────────────────────────────────*/
static uint8_t  s_oled_page    = OLED_PAGE_MAP;
static uint32_t s_last_oled_ms = 0;
static uint32_t s_last_imu_ms  = 0;
static uint32_t s_last_us_ms   = 0;
static uint8_t  s_us_index     = 0;    /* which sensor to trigger next */

static MPU6500_RawData  s_imu_raw  = {0};
static HMC5883L_RawData s_mag_raw  = {0};
static Orientation      s_orient   = {0};
static RobotPose        s_pose     = {0};

/* Sensor status flags set during Init */
static uint8_t s_mpu_ok = 0;
static uint8_t s_hmc_ok = 0;

/* ═══════════════════════════════════════════════════════════════ */
/*  OLED MAP PAGE renderer                                         */
/*  Draws 8 × 4 = 32 blocks of 16 × 16 pixels.                    */
/*  ┌──────────────────────────────────────────────────────────┐   */
/*  │  UNKNOWN  = white outline only                           │   */
/*  │  CLEAN    = white fill                                   │   */
/*  │  OBSTACLE = white fill + 10×10 black centre             │   */
/*  │  ROBOT    = 4×4 black square at cell centre             │   */
/*  └──────────────────────────────────────────────────────────┘   */
/* ═══════════════════════════════════════════════════════════════ */
static void render_map_page(void)
{
    int vx0, vy0;
    Map_GetViewport(&g_map, &vx0, &vy0);

    int robot_cx = Map_RobotCellX(&g_map);
    int robot_cy = Map_RobotCellY(&g_map);

    SSD1306_Fill(SSD1306_COLOR_BLACK);

    for (int row = 0; row < VIEW_ROWS; row++) {
        for (int col = 0; col < VIEW_COLS; col++) {

            int   grid_x = vx0 + col;
            int   grid_y = vy0 + row;
            uint8_t cell = Map_GetCell(&g_map, grid_x, grid_y);

            uint16_t px = (uint16_t)(col * BLOCK_PX);
            uint16_t py = (uint16_t)(row * BLOCK_PX);

            switch (cell) {

                case CELL_UNKNOWN:
                    /* White border, 1 px thick                    */
                    SSD1306_DrawRectangle(px, py,
                                          BLOCK_PX, BLOCK_PX,
                                          SSD1306_COLOR_WHITE);
                    break;

                case CELL_FREE:
                    /* Fully white (cleaned)                       */
                    SSD1306_DrawFilledRectangle(px, py,
                                                BLOCK_PX, BLOCK_PX,
                                                SSD1306_COLOR_WHITE);
                    break;

                case CELL_OCCUPIED:
                    /* White block with 10×10 black obstacle mark  */
                    SSD1306_DrawFilledRectangle(px, py,
                                                BLOCK_PX, BLOCK_PX,
                                                SSD1306_COLOR_WHITE);
                    SSD1306_DrawFilledRectangle(
                        px + OBSTACLE_OFF, py + OBSTACLE_OFF,
                        OBSTACLE_PX, OBSTACLE_PX,
                        SSD1306_COLOR_BLACK);
                    break;

                default: break;
            }

            /* ── Robot marker ────────────────────────────────── */
            if (grid_x == robot_cx && grid_y == robot_cy) {
                /* 4×4 black square at block centre on cleaned cell,
                   4×4 white square on unknown cell               */
                SSD1306_COLOR_t marker =
                    (cell == CELL_UNKNOWN) ? SSD1306_COLOR_WHITE
                                           : SSD1306_COLOR_BLACK;
                SSD1306_DrawFilledRectangle(px + 6, py + 6,
                                             4, 4, marker);
            }
        }
    }

    SSD1306_UpdateScreen();
}

/* ═══════════════════════════════════════════════════════════════ */
/*  OLED ULTRASONIC PAGE                                            */
/* ═══════════════════════════════════════════════════════════════ */
static void render_ultrasonic_page(void)
{
    char buf[22];
    SSD1306_Fill(SSD1306_COLOR_BLACK);

    /* Header */
    SSD1306_GotoXY(0, 0);
    SSD1306_Puts("-- Ultrasonic --", &Font_7x10, SSD1306_COLOR_WHITE);

    /* Sensor angles: 0=Front, 1=Right, 2=Rear, 3=Left            */
    static const char * const labels[4] = {"F", "R", "B", "L"};
    float d[4];
    for (int i = 0; i < 4; i++) {
        d[i] = ULTRASONIC_GetDistance(i);
    }

    /* Row 1: Front + Right */
    if (d[0] >= 0.0f)
        snprintf(buf, sizeof(buf), "F:%5.2fm", (double)d[0]);
    else
        snprintf(buf, sizeof(buf), "F: ----m");
    SSD1306_GotoXY(0, 14);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    if (d[1] >= 0.0f)
        snprintf(buf, sizeof(buf), "R:%5.2fm", (double)d[1]);
    else
        snprintf(buf, sizeof(buf), "R: ----m");
    SSD1306_GotoXY(65, 14);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    /* Row 2: Rear + Left */
    if (d[2] >= 0.0f)
        snprintf(buf, sizeof(buf), "B:%5.2fm", (double)d[2]);
    else
        snprintf(buf, sizeof(buf), "B: ----m");
    SSD1306_GotoXY(0, 28);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    if (d[3] >= 0.0f)
        snprintf(buf, sizeof(buf), "L:%5.2fm", (double)d[3]);
    else
        snprintf(buf, sizeof(buf), "L: ----m");
    SSD1306_GotoXY(65, 28);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    /* Row 3: status bar */
    snprintf(buf, sizeof(buf), "MPU:%s HMC:%s",
             s_mpu_ok ? "OK" : "ER",
             s_hmc_ok ? "OK" : "ER");
    SSD1306_GotoXY(0, 42);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    /* Row 4: sound speed reminder */
    SSD1306_GotoXY(0, 54);
    SSD1306_Puts("V=349.5m/s @30C", &Font_7x10, SSD1306_COLOR_WHITE);

    SSD1306_UpdateScreen();
}

/* ═══════════════════════════════════════════════════════════════ */
/*  OLED IMU PAGE                                                   */
/* ═══════════════════════════════════════════════════════════════ */
static void render_imu_page(void)
{
    char buf[22];
    SSD1306_Fill(SSD1306_COLOR_BLACK);

    SSD1306_GotoXY(0, 0);
    SSD1306_Puts("---- IMU ----", &Font_7x10, SSD1306_COLOR_WHITE);

    /* Gyro rates in deg/s */
    float gx = s_imu_raw.gx / 131.0f;
    float gy = s_imu_raw.gy / 131.0f;
    float gz = s_imu_raw.gz / 131.0f;

    snprintf(buf, sizeof(buf), "Gx%+6.1f Gy%+6.1f", (double)gx, (double)gy);
    SSD1306_GotoXY(0, 14);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    snprintf(buf, sizeof(buf), "Gz%+6.1f d/s", (double)gz);
    SSD1306_GotoXY(0, 28);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    /* Roll / Pitch / Yaw */
    snprintf(buf, sizeof(buf), "R%+6.1f P%+6.1f",
             (double)s_orient.roll, (double)s_orient.pitch);
    SSD1306_GotoXY(0, 42);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    snprintf(buf, sizeof(buf), "Yaw: %6.1f deg", (double)s_orient.yaw);
    SSD1306_GotoXY(0, 54);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    SSD1306_UpdateScreen();
}

/* ═══════════════════════════════════════════════════════════════ */
/*  OLED POSITION PAGE                                              */
/* ═══════════════════════════════════════════════════════════════ */
static void render_position_page(void)
{
    char buf[22];
    SSD1306_Fill(SSD1306_COLOR_BLACK);

    SSD1306_GotoXY(0, 0);
    SSD1306_Puts("-- Position --", &Font_7x10, SSD1306_COLOR_WHITE);

    snprintf(buf, sizeof(buf), "X: %7.3f m", (double)s_pose.x);
    SSD1306_GotoXY(0, 14);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    snprintf(buf, sizeof(buf), "Y: %7.3f m", (double)s_pose.y);
    SSD1306_GotoXY(0, 28);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    snprintf(buf, sizeof(buf), "H: %6.1f deg", (double)s_pose.theta);
    SSD1306_GotoXY(0, 42);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    snprintf(buf, sizeof(buf), "Spd:%4.2fm/s Cl:%lu",
             (double)ODOM_GetSpeed(),
             (unsigned long)g_map.cells_cleaned);
    SSD1306_GotoXY(0, 54);
    SSD1306_Puts(buf, &Font_7x10, SSD1306_COLOR_WHITE);

    SSD1306_UpdateScreen();
}

/* ═══════════════════════════════════════════════════════════════ */
/*  GENERAL_Init                                                    */
/* ═══════════════════════════════════════════════════════════════ */
void GENERAL_Init(void)
{
    /* ── OLED ────────────────────────────────────────────────── */
    ssd1306_I2C_SetHandle(&hi2c2);
    SSD1306_Init();
    SSD1306_Fill(SSD1306_COLOR_BLACK);
    SSD1306_GotoXY(16, 20);
    SSD1306_Puts("Floor Robot", &Font_11x18, SSD1306_COLOR_WHITE);
    SSD1306_GotoXY(20, 44);
    SSD1306_Puts("Initialising...", &Font_7x10, SSD1306_COLOR_WHITE);
    SSD1306_UpdateScreen();

    /* ── MPU6500 ─────────────────────────────────────────────── */
    if (MPU6500_Check(&hi2c1) == MPU_OK) {
        MPU6500_Init();   /* includes CalibrateGyro (~1 s) */
        s_mpu_ok = 1;
    }

    /* ── HMC5883L ────────────────────────────────────────────── */
    if (HMC5883L_Check(&hi2c1) == HMC_OK) {
        HMC5883L_Init();
        s_hmc_ok = 1;
    }

    /* ── Ultrasonic ──────────────────────────────────────────── */
    ULTRASONIC_Init();

    /* ── Buttons ─────────────────────────────────────────────── */
    BTNS_Init();

    /* ── Orientation filter ──────────────────────────────────── */
    STABLE_Init();

    /* ── Odometry + Map ─────────────────────────────────────── */
    ODOM_Init();
    Map_Init(&g_map);

    /* Splash hold */
    HAL_Delay(500);
    SSD1306_Fill(SSD1306_COLOR_BLACK);
    SSD1306_UpdateScreen();
}

/* ═══════════════════════════════════════════════════════════════ */
/*  GENERAL_Update — call from main() while(1) loop               */
/* ═══════════════════════════════════════════════════════════════ */
void GENERAL_Update(void)
{
    uint32_t now = HAL_GetTick();

    /* ── Buttons ─────────────────────────────────────────────── */
    BTNS_Update();
    if (BTNS_Get_OLEDPage() == BTN_PRESSED) {
        s_oled_page = (s_oled_page + 1) % OLED_NUM_PAGES;
    }

    /* ── IMU + Orientation (10 ms period = 100 Hz) ───────────── */
    if ((now - s_last_imu_ms) >= IMU_UPDATE_INTERVAL_MS) {
        float dt = (float)(now - s_last_imu_ms) * 0.001f;
        s_last_imu_ms = now;

        if (s_mpu_ok) MPU6500_ReadRaw(&s_imu_raw);
        if (s_hmc_ok) HMC5883L_ReadRaw(&s_mag_raw);

        STABLE_Update(&s_imu_raw, &s_mag_raw, dt);
        s_orient = STABLE_GetOrientation();

        /* Update position from IMU (motors off — manual push)    */
        ODOM_UpdateIMU(&s_imu_raw, s_orient.yaw, dt);
        s_pose = ODOM_GetPose();

        /* Mark current cell as cleaned                           */
        Map_UpdateRobotPose(&g_map,
                             s_pose.x, s_pose.y, s_pose.theta);
    }

    /* ── Ultrasonic round-robin (25 ms per sensor) ───────────── */
    if ((now - s_last_us_ms) >= US_TRIGGER_INTERVAL_MS) {
        s_last_us_ms = now;
        ULTRASONIC_CheckTimeout();

        /* Read the sensor that was triggered last period          */
        uint8_t read_idx = (s_us_index + 3) % 4;   /* previous index */
        float dist = ULTRASONIC_GetDistance(read_idx);

        static const float sensor_angles[4] = {
            US_ANGLE_0, US_ANGLE_1, US_ANGLE_2, US_ANGLE_3
        };

        if (dist > 0.05f) {   /* > 5 cm = plausible reading       */
            Map_UpdateUltrasonic(&g_map, dist, sensor_angles[read_idx]);
        }

        /* Trigger the next sensor                                 */
        ULTRASONIC_Trigger(s_us_index);
        s_us_index = (s_us_index + 1) % 4;
    }

    /* ── OLED refresh (200 ms = 5 Hz) ───────────────────────── */
    if ((now - s_last_oled_ms) >= OLED_UPDATE_INTERVAL_MS) {
        s_last_oled_ms = now;

#if ENABLE_OLED_DEBUG
        GENERAL_OLED_Debug();
#endif
    }
}

/* ─────────────────────────────────────────────────────────────── */
void GENERAL_ResetPose(void)
{
    ODOM_SetPose(15.0f, 15.0f, 0.0f);
    ODOM_ResetVelocity();
    s_pose = ODOM_GetPose();
}

/* ─────────────────────────────────────────────────────────────── */
#if ENABLE_OLED_DEBUG
void GENERAL_OLED_Debug(void)
{
    switch (s_oled_page) {
        case OLED_PAGE_MAP:        render_map_page();        break;
        case OLED_PAGE_ULTRASONIC: render_ultrasonic_page(); break;
        case OLED_PAGE_IMU:        render_imu_page();        break;
        case OLED_PAGE_POSITION:   render_position_page();   break;
        default:                   render_map_page();        break;
    }
}
#endif

/* ─────────────────────────────────────────────────────────────── */
#if ENABLE_OLED_SELFTEST
void GENERAL_OLED_SelfTest(void)
{
    /* Draw all block types across the screen */
    SSD1306_Fill(SSD1306_COLOR_BLACK);

    /* Row 0: unknown blocks (outlines) */
    for (int c = 0; c < VIEW_COLS; c++) {
        SSD1306_DrawRectangle(c * 16, 0, 16, 16, SSD1306_COLOR_WHITE);
    }
    /* Row 1: clean blocks */
    for (int c = 0; c < VIEW_COLS; c++) {
        SSD1306_DrawFilledRectangle(c * 16, 16, 16, 16, SSD1306_COLOR_WHITE);
    }
    /* Row 2: obstacle blocks */
    for (int c = 0; c < VIEW_COLS; c++) {
        SSD1306_DrawFilledRectangle(c * 16, 32, 16, 16, SSD1306_COLOR_WHITE);
        SSD1306_DrawFilledRectangle(c * 16 + 3, 35, 10, 10,
                                     SSD1306_COLOR_BLACK);
    }
    /* Row 3: robot marker */
    for (int c = 0; c < VIEW_COLS; c++) {
        SSD1306_DrawRectangle(c * 16, 48, 16, 16, SSD1306_COLOR_WHITE);
    }
    /* Robot at cell (2, 3) */
    SSD1306_DrawFilledRectangle(2 * 16 + 6, 48 + 6, 4, 4,
                                 SSD1306_COLOR_WHITE);

    SSD1306_UpdateScreen();
}
#endif
