#include "general.h"
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

/* ── I2C handles (generated by CubeMX) ─────────────────────────
   hi2c1 : PB6/PB7  → MPU6050 + HMC5883L
   hi2c2 : PB10/PB11 → SSD1306 OLED                             */
extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c2;

/* ── Global map (declared here, extern'd in general.h) ─────────*/
Map g_map;

/* ── Module-private state ───────────────────────────────────────*/
static uint8_t  s_oled_page    = OLED_PAGE_MAP;
static uint32_t s_last_oled_ms = 0;
static uint32_t s_last_imu_ms  = 0;
static uint32_t s_last_us_ms   = 0;
static uint32_t s_last_btn_ms  = 0;
static uint8_t  s_us_index     = 0;    /* which sensor to trigger next */

/* CORRECTED: MPU6050_RawData instead of MPU6500 */
static MPU6050_RawData  s_imu_raw  = {0};
static HMC5883L_RawData s_mag_raw  = {0};
static Orientation      s_orient   = {0};
static RobotPose        s_pose     = {0};

/* Sensor status flags set during Init */
static uint8_t s_mpu_ok = 0;
static uint8_t s_hmc_ok = 0;

typedef enum {
    MODE_WALL_FOLLOW,
    MODE_COVERAGE,
    MODE_IDLE
} RobotMode;

static RobotMode s_robot_mode = MODE_COVERAGE; /* Start by tracing the walls */

/* ADD THIS NEW AVOIDANCE STATE MACHINE */
typedef enum {
    AVOID_FORWARD,
    AVOID_TURN_LEFT,
    AVOID_TURN_RIGHT
} AvoidState;

static AvoidState s_avoid_state = AVOID_FORWARD;

/* Variables to share motor speeds with the OLED display */
static int s_disp_l_pwm = 0;
static int s_disp_r_pwm = 0;

/* ═══════════════════════════════════════════════════════════════ */
/* OLED MAP PAGE renderer                                         */
/* Draws 8 × 4 = 32 blocks of 16 × 16 pixels.                    */
/* ┌──────────────────────────────────────────────────────────┐   */
/* │  UNKNOWN  = white outline only                           │   */
/* │  CLEAN    = white fill                                   │   */
/* │  OBSTACLE = white fill + 10×10 black centre             │   */
/* │  ROBOT    = 4×4 black square at cell centre             │   */
/* └──────────────────────────────────────────────────────────┘   */
/* ═══════════════════════════════════════════════════════════════ */
static void render_map_page(void)
{
    int vx0, vy0;
    Map_GetViewport(&g_map, &vx0, &vy0);

    int robot_cx = Map_RobotCellX(&g_map);
    int robot_cy = Map_RobotCellY(&g_map);

    OLED_Clear();

    for (int row = 0; row < VIEW_ROWS; row++) {
        for (int col = 0; col < VIEW_COLS; col++) {

            int   grid_x = vx0 + col;
            int   grid_y = vy0 + row;
            uint8_t cell = Map_GetCell(&g_map, grid_x, grid_y);

            uint16_t px = (uint16_t)(col * BLOCK_PX);
            uint16_t py = (uint16_t)(row * BLOCK_PX);

            switch (cell) {

                case CELL_UNKNOWN:
                    /* White border, 1 px thick */
                    OLED_DrawOutline(px, py, BLOCK_PX, BLOCK_PX);
                    break;

                case CELL_FREE:
                    /* Fully white (cleaned) */
                    OLED_Rectangle(px, py, BLOCK_PX, BLOCK_PX);
                    break;

                case CELL_OCCUPIED:
                    /* White block with 10×10 black obstacle mark */
                    OLED_Rectangle(px, py, BLOCK_PX, BLOCK_PX);
                    OLED_ClearArea(px + OBSTACLE_OFF, py + OBSTACLE_OFF, OBSTACLE_PX, OBSTACLE_PX);
                    break;

                default: break;
            }

            /* ── Robot marker ────────────────────────────────── */
            if (grid_x == robot_cx && grid_y == robot_cy) {
                /* 4×4 black square at block centre on cleaned cell,
                   4×4 white square on unknown cell */
                if (cell == CELL_UNKNOWN) {
                    OLED_Rectangle(px + 6, py + 6, 4, 4);
                } else {
                    OLED_ClearArea(px + 6, py + 6, 4, 4);
                }
            }
        }
    }

    OLED_Update();
}

/* ═══════════════════════════════════════════════════════════════ */
/*  PAGE 1 — ULTRASONIC                                            */
/*                                                                  */
/*  FIX: last_dist[] caches the most recent valid reading per      */
/*  sensor. miss_count[] only shows NO ECHO after 4 consecutive    */
/*  missed echoes — prevents flashing caused by the brief window   */
/*  between Trigger() and CaptureCallback() firing.                */
/* ═══════════════════════════════════════════════════════════════ */

#define NO_ECHO_THRESHOLD  4   /* consecutive misses before showing NO ECHO */

static void render_ultrasonic_page(void)
{
    char line[32];
    const char    *labels[4] = {"F", "R", "B", "L"};
    const uint8_t  y_pos[4]  = {14, 24, 34, 44};

    OLED_Clear();
    OLED_Print(0, 0, "-- Ultrasonic Raw --");

    for (int i = 0; i < 4; i++) {
        /* If the sensor has a valid pulse, print the raw microseconds */
        if (ultrasonic[i].status == US_OK) {
            snprintf(line, sizeof(line), "%s: %lu us",
                     labels[i],
                     (unsigned long)ultrasonic[i].pulse_us);
        }
        /* Otherwise, print NO ECHO */
        else {
            snprintf(line, sizeof(line), "%s: NO ECHO", labels[i]);
        }

        OLED_Print(0, y_pos[i], line);
    }

    /* Bottom row: IMU sensor status */
    snprintf(line, sizeof(line), "MPU:%s HMC:%s",
             s_mpu_ok ? "OK" : "ERR",
             s_hmc_ok ? "OK" : "ERR");
    OLED_Print(0, 54, line);

    OLED_Update();
}

/* ═══════════════════════════════════════════════════════════════ */
/* OLED IMU PAGE                                                  */
/* ═══════════════════════════════════════════════════════════════ */
static void render_imu_page(void)
{
	char line[32]; // 16 bytes is plenty for a short label and an integer

	    OLED_Clear();

	    /* ── 1. Sensor Status (Using the flags from general.c) ── */
	    if (s_mpu_ok) OLED_Print(0, 0, "MPU:OK");
	    else          OLED_Print(0, 0, "MPU:ERR");

	    if (s_hmc_ok) OLED_Print(0, 10, "HMC:OK");
	    else          OLED_Print(0, 10, "HMC:ERR");

	    /* ── 2. Magnetometer Raw Data ── */
	    snprintf(line, sizeof(line), "MX:%-6d", (int)s_mag_raw.mx);
	    OLED_Print(0, 26, line);

	    snprintf(line, sizeof(line), "MY:%-6d", (int)s_mag_raw.my);
	    OLED_Print(0, 36, line);

	    snprintf(line, sizeof(line), "MZ:%-6d", (int)s_mag_raw.mz);
	    OLED_Print(0, 46, line);

	    /* ── 3. Accelerometer Raw Data ── */
	    snprintf(line, sizeof(line), "AX:%-6d", (int)s_imu_raw.ax);
	    OLED_Print(60, 0, line);

	    snprintf(line, sizeof(line), "AY:%-6d", (int)s_imu_raw.ay);
	    OLED_Print(60, 10, line);

	    snprintf(line, sizeof(line), "AZ:%-6d", (int)s_imu_raw.az);
	    OLED_Print(60, 20, line);

	    /* ── 4. Gyroscope Raw Data ── */
	    snprintf(line, sizeof(line), "GX:%-6d", (int)s_imu_raw.gx);
	    OLED_Print(60, 30, line);

	    snprintf(line, sizeof(line), "GY:%-6d", (int)s_imu_raw.gy);
	    OLED_Print(60, 40, line);

	    snprintf(line, sizeof(line), "GZ:%-6d", (int)s_imu_raw.gz);
	    OLED_Print(60, 50, line);

	    OLED_Update();
}

/* ═══════════════════════════════════════════════════════════════ */
/* OLED POSITION PAGE                                             */
/* ═══════════════════════════════════════════════════════════════ */
static void render_position_page(void)
{
    char buf[22];
    OLED_Clear();

    OLED_Print(0, 0, "-- Position --");

    snprintf(buf, sizeof(buf), "X: %7.3f m", (double)s_pose.x);
    OLED_Print(0, 12, buf);

    snprintf(buf, sizeof(buf), "Y: %7.3f m", (double)s_pose.y);
    OLED_Print(0, 22, buf);

    snprintf(buf, sizeof(buf), "H: %6.1f deg", (double)s_pose.theta);
    OLED_Print(0, 32, buf);

    snprintf(buf, sizeof(buf), "Spd:%4.2fm/s Cl:%lu",
             (double)ODOM_GetSpeed(),
             (unsigned long)g_map.cells_cleaned);
    OLED_Print(0, 44, buf);

    OLED_Update();
}

/* ═══════════════════════════════════════════════════════════════ */
/* OLED DIRECTION PAGE (New Page 2)                               */
/* ═══════════════════════════════════════════════════════════════ */
static void render_direction_page(void)
{
    OLED_Clear();
    OLED_Print(0, 0, "-- Motor Status --");

    char buf[32];
    snprintf(buf, sizeof(buf), "L PWM: %d", s_disp_l_pwm);
    OLED_Print(0, 16, buf);

    snprintf(buf, sizeof(buf), "R PWM: %d", s_disp_r_pwm);
    OLED_Print(0, 26, buf);

    /* Determine the driving state based on PWM signs */
    const char* state_str = "STOPPED";

    if (s_disp_l_pwm > 0 && s_disp_r_pwm > 0)      state_str = "FORWARD";
    else if (s_disp_l_pwm < 0 && s_disp_r_pwm < 0) state_str = "BACKWARD";
    else if (s_disp_l_pwm < 0 && s_disp_r_pwm > 0) state_str = "ROTATING LEFT";
    else if (s_disp_l_pwm > 0 && s_disp_r_pwm < 0) state_str = "ROTATING RIGHT";

    OLED_Print(0, 44, "Action:");
    OLED_Print(0, 54, state_str);

    OLED_Update();
}

/* ═══════════════════════════════════════════════════════════════ */
/* GENERAL_Init                                                   */
/* ═══════════════════════════════════════════════════════════════ */
void GENERAL_Init(void)
{
    /* ── OLED ────────────────────────────────────────────────── */
    OLED_Init(&hi2c2);
    OLED_Clear();

    /* Using your OLED wrapper to print splash screen text */
    OLED_Print(16, 20, "Floor Robot");
    OLED_Print(20, 44, "Initialising...");
    OLED_Update();

    /* ── MPU6050 ─────────────────────────────────────────────── */
    if (MPU6050_Check(&hi2c1) == MPU_OK) {
        MPU6050_Init();   /* includes CalibrateGyro (~1 s) */
        s_mpu_ok = 1;
    }

    /* ── HMC5883L ────────────────────────────────────────────── */
    if (HMC5883L_Check(&hi2c1) == HMC_OK) {
        HMC5883L_Init();
        s_hmc_ok = 1;
    }

    /* ── Ultrasonic ──────────────────────────────────────────── */
    ULTRASONIC_Init();

    /* ── Buttons ─────────────────────────────────────────────── */
    BTNS_Init();

    /* ── Orientation filter ──────────────────────────────────── */
    STABLE_Init();

    /* ── Odometry + Map ─────────────────────────────────────── */
    ODOM_Init();
    Map_Init(&g_map);

    COVERAGE_Init();
	MOTION_Init();
	ENCODER_Init();

    /* Splash hold */
    HAL_Delay(500);
    OLED_Clear();
    OLED_Update();

    MOTOR_Init();         /* Initializes the motor arrays */
	MOTORPWM_Init();      /* Initializes the PWM variables */
	MOTOR_WakeAll();      /* WAKES UP THE MOTOR DRIVERS! */

	/* --- TEMPORARY MOTOR DIRECTION TEST --- */
	    /* Force both motors FORWARD at 50% speed for 5 seconds */
	    MOTOR_Set(0, MOTOR_FORWARD, 300); /* Motor 1 (Left) */
	    MOTOR_Set(1, MOTOR_FORWARD, 300); /* Motor 2 (Right) */

	    HAL_Delay(3000);

	    /* Stop motors before entering the main loop */
	    MOTOR_Set(0, 0, 0);
	    MOTOR_Set(1, 0, 0);
	    /* -------------------------------------- */

	/* ADD THESE LINES TO FIX THE 30m TELEPORT BUG: */
	/* 1. Clear any fake encoder noise that happened during boot */
	ENCODER_Reset(0);
	ENCODER_Reset(1);

	/* 2. Reset the stopwatches so 'dt' is perfectly 0.01s on loop 1! */
	s_last_imu_ms  = HAL_GetTick();
	s_last_us_ms   = HAL_GetTick();
	s_last_oled_ms = HAL_GetTick();
}

/* ═══════════════════════════════════════════════════════════════ */
/* GENERAL_Update — call from main() while(1) loop               */
/* ═══════════════════════════════════════════════════════════════ */
void GENERAL_Update(void)
{
    uint32_t now = HAL_GetTick();

    /* ── Buttons ─────────────────────────────────────────────── */
    BTNS_Update();
    if (BTNS_Get_OLEDPage() == BTN_PRESSED) {
            /* Only allow a page change if 500ms have passed since the last one */
            if ((now - s_last_btn_ms) > 500) {
                s_oled_page = (s_oled_page + 1) % OLED_NUM_PAGES;
                s_last_btn_ms = now; /* Reset the cooldown timer */
            }
        }

    /* ── Autonomous Loop (10 ms period = 100 Hz) ───────────── */
    if ((now - s_last_imu_ms) >= IMU_UPDATE_INTERVAL_MS) {
        float dt = (float)(now - s_last_imu_ms) * 0.001f;
        s_last_imu_ms = now;

        /* 1. Read IMU (Kept active ONLY for the OLED Display!) */
        if (s_mpu_ok) MPU6050_ReadRaw(&s_imu_raw);
        if (s_hmc_ok) HMC5883L_ReadRaw(&s_mag_raw);
        STABLE_Update(&s_imu_raw, &s_mag_raw, dt);
        s_orient = STABLE_GetOrientation();

        /* 2. Read Encoders and convert to m/s */
        float v_left  = ENCODER_GetSpeed(0) * 0.0325f;
        float v_right = ENCODER_GetSpeed(1) * 0.0325f;

        if (MOTOR_GetDirection(0) < 0) v_left  = -v_left;
        if (MOTOR_GetDirection(1) < 0) v_right = -v_right;

        /* 3. Update Odometry Position (For OLED) */
        ODOM_UpdateEncoders(v_left, v_right, s_orient.yaw, dt);
        s_pose = ODOM_GetPose();

        /* 4. Read 4 Ultrasonic Sensors */
                float dist_F = ULTRASONIC_GetDistance(0); /* SR1: Front */
                float dist_R = ULTRASONIC_GetDistance(1); /* SR2: Right */
                float dist_L = ULTRASONIC_GetDistance(3); /* SR4: Left  */

                /* Step 4a: Check RAW sensor data (1cm to 30cm) */
                int raw_obs_F = (dist_F > 0.01f && dist_F < 0.30f) ? 1 : 0;
                int obs_R     = (dist_R > 0.01f && dist_R < 0.30f) ? 1 : 0;
                int obs_L     = (dist_L > 0.01f && dist_L < 0.30f) ? 1 : 0;

                /* Step 4b: DEBOUNCE FILTER FOR SR1 (FRONT) */
                static int f_block_count = 0;
                int obs_F = 0; /* This is the final confirmed obstacle state */

                if (raw_obs_F == 1) {
                    f_block_count++;

                    /* 30 ticks * 10ms = 300ms (Exactly 3 continuous sensor updates!) */
                    if (f_block_count >= 30) {
                        obs_F = 1;              /* The wall is real! */
                        f_block_count = 30;     /* Cap the counter so it doesn't overflow */
                    }
                } else {
                    /* If the sensor suddenly sees a clear path, instantly reset */
                    f_block_count = 0;
                    obs_F = 0;
                }

        int left_pwm = 0;
        int right_pwm = 0;

        /* 5. Master State Machine */
        if (s_robot_mode == MODE_COVERAGE)
        {
            if (s_avoid_state == AVOID_FORWARD)
            {
                if (obs_F) {
                    /* Front is blocked! Decide which way to turn */
                    if (obs_L && !obs_R) {
                        /* Front & Left blocked -> Turn Right */
                        s_avoid_state = AVOID_TURN_RIGHT;
                    } else {
                        /* Front & Right blocked (or only Front) -> Turn Left */
                        s_avoid_state = AVOID_TURN_LEFT;
                    }
                } else {
                    /* Front is clear. Drive straight using Encoders! */
                    int base_speed = 300;

                    /* Calculate error: If left is spinning faster than right, err is positive */
                    //float speed_error = v_left - v_right;

                    /* Proportional Controller: Adjust PWM to equalize wheel speeds */
                    //int correction = (int)(speed_error * 1000.0f);

                    left_pwm  = base_speed; //- correction;
                    right_pwm = base_speed; //+ correction;
                }
            }
            else if (s_avoid_state == AVOID_TURN_LEFT)
            {
                /* Rotate in place */
                left_pwm  = -250;
                right_pwm =  250;

                /* Keep turning until SR1 (Front) is clear */
                if (!obs_F) {
                    s_avoid_state = AVOID_FORWARD;
                }
            }
            else if (s_avoid_state == AVOID_TURN_RIGHT)
            {
                /* Rotate in place */
                left_pwm  =  250;
                right_pwm = -250;

                /* Keep turning until SR1 (Front) is clear */
                if (!obs_F) {
                    s_avoid_state = AVOID_FORWARD;
                }
            }
        }

        /* 6. Drive Physical Motors */
        uint8_t left_dir  = (left_pwm >= 0)  ? MOTOR_FORWARD : MOTOR_BACKWARD;
        uint8_t right_dir = (right_pwm >= 0) ? MOTOR_FORWARD : MOTOR_BACKWARD;

        MOTOR_Set(0, left_dir,  abs(left_pwm));
        MOTOR_Set(1, right_dir, abs(right_pwm));

        /* Save for OLED Page 2 */
        s_disp_l_pwm = left_pwm;
        s_disp_r_pwm = right_pwm;
    }

    /* ── Ultrasonic round-robin (25 ms per sensor) ───────────── */
    if ((now - s_last_us_ms) >= US_TRIGGER_INTERVAL_MS) {
        s_last_us_ms = now;
        ULTRASONIC_CheckTimeout();

        uint8_t read_idx = (s_us_index + 3) % 4;
        float dist = ULTRASONIC_GetDistance(read_idx);

        /* Mapping disabled for now
        if (dist > 0.05f) {
            Map_UpdateUltrasonic(&g_map, dist, sensor_angles[read_idx]);
        } */

        ULTRASONIC_Trigger(s_us_index);
        s_us_index = (s_us_index + 1) % 4;
    }

    /* ── OLED refresh (200 ms = 5 Hz) ───────────────────────── */
    if ((now - s_last_oled_ms) >= OLED_UPDATE_INTERVAL_MS) {
        s_last_oled_ms = now;

#if ENABLE_OLED_DEBUG
        GENERAL_OLED_Debug();
#endif
    }
}

/* ─────────────────────────────────────────────────────────────── */
void GENERAL_ResetPose(void)
{
    ODOM_SetPose(15.0f, 15.0f, 0.0f);
    ODOM_ResetVelocity();
    s_pose = ODOM_GetPose();
}

/* ─────────────────────────────────────────────────────────────── */
#if ENABLE_OLED_DEBUG
void GENERAL_OLED_Debug(void)
{
	switch (s_oled_page) {
		case 0:  render_map_page();        break; /* Page 1 */
		case 1:  render_direction_page();  break; /* Page 2: NEW DIRECTION PAGE! */
		case 2:  render_ultrasonic_page(); break; /* Page 3 */
		case 3:  render_imu_page();        break; /* Page 4 */
		case 4:  render_position_page();   break; /* Page 5 */
		default: render_map_page();        break;
    }
}
#endif

/* ─────────────────────────────────────────────────────────────── */
#if ENABLE_OLED_SELFTEST
void GENERAL_OLED_SelfTest(void)
{
    /* Draw all block types across the screen */
    OLED_Clear();

    /* Row 0: unknown blocks (outlines) */
    for (int c = 0; c < VIEW_COLS; c++) {
        OLED_DrawOutline(c * 16, 0, 16, 16);
    }
    /* Row 1: clean blocks */
    for (int c = 0; c < VIEW_COLS; c++) {
        OLED_Rectangle(c * 16, 16, 16, 16);
    }
    /* Row 2: obstacle blocks */
    for (int c = 0; c < VIEW_COLS; c++) {
        OLED_Rectangle(c * 16, 32, 16, 16);
        OLED_ClearArea(c * 16 + 3, 35, 10, 10);
    }
    /* Row 3: robot marker */
    for (int c = 0; c < VIEW_COLS; c++) {
        OLED_DrawOutline(c * 16, 48, 16, 16);
    }
    /* Robot at cell (2, 3) */
    OLED_Rectangle(2 * 16 + 6, 48 + 6, 4, 4);

    OLED_Update();
}
#endif
