#include "ultrasonic.h"

/* TIM2 handle generated by CubeMX (Input Capture, 1 MHz clock)  */
extern TIM_HandleTypeDef htim2;

/* ── Module state ───────────────────────────────────────────────*/
ULTRASONIC_Data ultrasonic[4] = {0};

static uint32_t echo_start[4]  = {0};
static uint8_t  echo_active[4] = {0};  /* 1 = waiting for falling edge */
static uint32_t trig_time_ms[4]= {0};  /* for timeout detection        */

/* Trigger GPIO (from main.h defines) */
static GPIO_TypeDef * const trig_port[4] = {
    TRIG1_GPIO_Port, TRIG2_GPIO_Port, TRIG3_GPIO_Port, TRIG4_GPIO_Port
};
static const uint16_t trig_pin[4] = {
    TRIG1_Pin, TRIG2_Pin, TRIG3_Pin, TRIG4_Pin
};

/* ─────────────────────────────────────────────────────────────── */
void ULTRASONIC_Init(void)
{
    for (int i = 0; i < 4; i++) {
        ultrasonic[i].pulse_us   = 0;
        ultrasonic[i].distance_m = -1.0f;
        ultrasonic[i].ready      = 0;
        ultrasonic[i].status     = US_NO_ECHO;
        echo_active[i]           = 0;
    }

    /* Start input-capture interrupts on all four channels.
       HAL_TIM_IC_CaptureCallback lives in stm32f4xx_it.c —
       NOT here — to avoid duplicate symbol linker error.          */
    HAL_TIM_IC_Start_IT(&htim2, TIM_CHANNEL_1);
    HAL_TIM_IC_Start_IT(&htim2, TIM_CHANNEL_2);
    HAL_TIM_IC_Start_IT(&htim2, TIM_CHANNEL_3);
    HAL_TIM_IC_Start_IT(&htim2, TIM_CHANNEL_4);
}

/* ─────────────────────────────────────────────────────────────── */
/*  ULTRASONIC_Trigger                                              */
/*  Sends a >=10 µs HIGH pulse on the TRIG pin.                    */
/*  At 168 MHz core: 1680 NOP ≈ 10 µs.                             */
/*                                                                  */
/*  FIX: distance_m and status are NOT reset here.                  */
/*  They keep the last good value until CheckTimeout() decides      */
/*  the sensor genuinely missed an echo. This prevents the display  */
/*  from flashing NO ECHO between every trigger/echo cycle.         */
/* ─────────────────────────────────────────────────────────────── */
void ULTRASONIC_Trigger(uint8_t index)
{
    if (index >= 4) return;

    HAL_GPIO_WritePin(trig_port[index], trig_pin[index], GPIO_PIN_SET);
    volatile uint32_t cnt = 1680;
    while (cnt--) { __NOP(); }
    HAL_GPIO_WritePin(trig_port[index], trig_pin[index], GPIO_PIN_RESET);

    ultrasonic[index].ready      = 0;
    //ultrasonic[index].status     = US_NO_ECHO;
    //ultrasonic[index].distance_m = -1.0f;
    echo_active[index]           = 0;
    trig_time_ms[index]          = HAL_GetTick();
}

/* ─────────────────────────────────────────────────────────────── */
/*  ULTRASONIC_CaptureCallback                                     */
/*  Called from HAL_TIM_IC_CaptureCallback (see bottom of file).   */
/*  TIM2 @ 1 MHz → CCR value in microseconds.                      */
/*  Both-edge mode: odd call = rising, even call = falling.        */
/* ─────────────────────────────────────────────────────────────── */
/* ─────────────────────────────────────────────────────────────── */
/* ULTRASONIC_CaptureCallback                                     */
/* Accepts sensor index (0, 1, 2, 3) from stm32f4xx_it.c          */
/* ─────────────────────────────────────────────────────────────── */
void ULTRASONIC_CaptureCallback(uint8_t idx)
{
    uint32_t ccr;

    /* Get the correct Capture/Compare Register value based on index */
    if (idx == 0)      ccr = htim2.Instance->CCR1;
    else if (idx == 1) ccr = htim2.Instance->CCR2;
    else if (idx == 2) ccr = htim2.Instance->CCR3;
    else if (idx == 3) ccr = htim2.Instance->CCR4;
    else return;

    if (!echo_active[idx]) {
        /* ── Rising edge: record start time ─────────────────── */
        echo_start[idx]  = ccr;
        echo_active[idx] = 1;
    } else {
        /* ── Falling edge: compute pulse width ──────────────── */
        uint32_t pulse;
        if (ccr >= echo_start[idx]) {
            pulse = ccr - echo_start[idx];
        } else {
            /* Timer rollover (TIM2 is 32-bit so very rare)      */
            pulse = (0xFFFFFFFFUL - echo_start[idx]) + ccr + 1UL;
        }

        ultrasonic[idx].pulse_us   = pulse;
        ultrasonic[idx].distance_m = (pulse * US_SOUND_SPEED_MPS) / 2000000.0f;

        if (ultrasonic[idx].distance_m > US_MAX_DISTANCE_M) {
            ultrasonic[idx].distance_m = US_MAX_DISTANCE_M;
        }

        ultrasonic[idx].ready  = 1;
        ultrasonic[idx].status = US_OK;
        echo_active[idx]       = 0;
    }
}

/* ─────────────────────────────────────────────────────────────── */
/*  ULTRASONIC_CheckTimeout                                         */
/*  Call from GENERAL_Update() every loop tick.                     */
/*  Only marks US_NO_ECHO after US_TIMEOUT_MS with no echo —        */
/*  this is the ONLY place that invalidates distance_m.             */
/* ─────────────────────────────────────────────────────────────── */
void ULTRASONIC_CheckTimeout(void)
{
    uint32_t now = HAL_GetTick();
    for (int i = 0; i < 4; i++) {
        if (echo_active[i] && (now - trig_time_ms[i]) > US_TIMEOUT_MS) {
            echo_active[i]           = 0;
            ultrasonic[i].status     = US_NO_ECHO;
            ultrasonic[i].distance_m = -1.0f;
        }
    }
}

/* ─────────────────────────────────────────────────────────────── */
/*  ULTRASONIC_GetDistance                                          */
/*  Returns distance in metres, or -1.0 if no valid reading.        */
/* ─────────────────────────────────────────────────────────────── */
float ULTRASONIC_GetDistance(uint8_t index)
{
    if (index >= 4)                              return -1.0f;
    if (ultrasonic[index].status == US_NO_ECHO)  return -1.0f;
    if (!ultrasonic[index].ready)                return -1.0f;
    return ultrasonic[index].distance_m;
}

